### ISSUE TITLE
Not compatible with IPB 4.3

### ISSUE THREAD

**Issue by megazloj** [VATSIM-UK/VatsimIPBoardAuth#2]
Hello! Can you please update SSO to be compatible with IPB 4.3?
I'm getting HTTP 500 code. I will give more details shortly.

**Comment by megazloj** [comment]
> Error: Call to undefined method IPS\Login::forms() (0)
> #0 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Theme/SandboxedTemplate.php(56): IPS\Theme\class_core_front_global->loginPopup(Object(IPS\Login))
> #1 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Theme/Theme.php(824) : eval()'d code(15314): IPS\Theme\_SandboxedTemplate->__call('loginPopup', Array)
> #2 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Theme/SandboxedTemplate.php(56): IPS\Theme\class_core_front_global->userBar()
> #3 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Theme/Theme.php(824) : eval()'d code(5934): IPS\Theme\_SandboxedTemplate->__call('userBar', Array)
> #4 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Theme/SandboxedTemplate.php(56): IPS\Theme\class_core_front_global->globalTemplate('611e6b96b0ff5b2...', '\n<div class='ip...', Array)
> #5 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Dispatcher/Dispatcher.php(166): IPS\Theme\_SandboxedTemplate->__call('globalTemplate', Array)
> #6 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Dispatcher/Standard.php(107): IPS\_Dispatcher->finish()
> #7 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Dispatcher/Front.php(569): IPS\Dispatcher\_Standard->finish()
> #8 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/system/Dispatcher/Dispatcher.php(148): IPS\Dispatcher\_Front->finish()
> #9 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/index.php(13): IPS\_Dispatcher->run()
> #10 {main}

> #0 /usr/www/sites/vacc-ua/forum43.vacc-ua.org/init.php(533): IPS\_Log::log('Error: Call to ...', 'uncaught_except...')
> #1 [internal function]: IPS\IPS::exceptionHandler(Object(Error))
> #2 {main}

**Comment by orbacht** [comment]
Im with the same problem too....
Did you manage to face with it?

**Comment by KiloSierraCharlie** [comment]
This is fixed by PR#3.
